### ISSUE TITLE
Hi. I have a problem to you

### ISSUE THREAD

**Issue by TranTrungPhong** [miguelarauj1o/CalendarQuickStart#4]
After run application.
Result : 
The follwing error occurred : 403 Forbidden
{
"code":403
"errors":[
{
"domain:"usageLimits",
"message":"Access Not Configured .........."
Hope to get a response from you

**Comment by miguelarauj1o** [comment]
@TranTrungPhong, maybe this link can help you: 
[Getting Error 403: Access Not Configured](http://stackoverflow.com/questions/22870082/getting-error-403-access-not-configured-please-use-google-developers-console-t)

or this

[OAuth2::Error usageLimits accessNotConfigured](https://github.com/zquestz/omniauth-google-oauth2/issues/111)
